name: Check and Deploy
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read
      statuses: write
      contents: write
      pull-requests: write
    env:
      PAYLOAD_TEST_USER_EMAIL: ${{ secrets.PAYLOAD_TEST_USER_EMAIL }}
      PAYLOAD_TEST_USER_PASSWORD: ${{ secrets.PAYLOAD_TEST_USER_PASSWORD }}
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Extract Chromium Archive
        run: node ./scripts/extract-chromium-archive.mjs
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Push Database Migrations
        run: npm run migrate:up
      - name: Run Playwright Tests
        run: npx playwright test --update-snapshots
      - name: Create Pull Request for Snapshot Updates
        if: ${{ !cancelled() }}
        uses: peter-evans/create-pull-request@v8
        with:
          branch: snapshot-updates/${{ github.event.client_payload.git.ref }}
          add-paths: e2e/**/__snapshots__/**
          title: "chore: update playwright test snapshots"
          body: |
            Updates Playwright test snapshot files changed in a GitHub Actions run.

            GitHub Actions Run: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Original Changes: [${{ github.event.client_payload.git.shortSha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.client_payload.git.sha }})

            *This pull request is automatically created by GitHub Actions.*
          commit-message: |
            chore: update playwright test snapshots

            GitHub Actions Run: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Original Changes: [${{ github.event.client_payload.git.shortSha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.client_payload.git.sha }})
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: Playwright Results
          path: .playwright-results/
          include-hidden-files: true
          retention-days: 14
  deployment:
    name: Production Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - e2e-tests
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Extract Chromium Archive
        run: node ./scripts/extract-chromium-archive.mjs
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Push Database Migrations
        run: npm run migrate:up
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
