name: Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
permissions:
  issues: write
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  prebuild:
    name: Prebuild (Preview)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
      - name: Install Dependencies
        run: npm ci
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Zip .next Directory
        # let's zip the .next directory to upload it as an artifact
        # because Next.js generates files with colons in their names like
        # node:fs, which is not supported to be uploaded as an artifact.
        run: zip -r .next.zip .next
      - run: ls -al
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: prebuild
          path: |
            .vercel/output
            .next.zip
          include-hidden-files: true
          retention-days: 1
          if-no-files-found: error
  deployment:
    name: Deployment (Preview)
    runs-on: ubuntu-latest
    needs: prebuild
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
      - name: Install Dependencies
        run: npm ci
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Download Build Artifacts
        uses: actions/download-artifact@v7
        with:
          name: prebuild
      - name: Unzip .next Directory
        # let's unzip the .next directory that was zipped in order to avoid
        # upload-artifact restrictions on filenames including colons.
        run: unzip .next.zip
      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: ls -al
      - name: Deploy Project Artifacts to Vercel
        id: deployment
        run: |
          npx vercel deploy \
            --prebuilt \
            --token=${{ secrets.VERCEL_TOKEN }} \
            > ${{ runner.temp }}/url.txt
          echo "url=$(cat ${{runner.temp}}/url.txt)" >> $GITHUB_OUTPUT
      - name: Previous Comment Retrieval
        uses: peter-evans/find-comment@v4
        id: previous-comment
        with:
          issue-number: ${{ github.event.number }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- deployment #${{ github.event.number }} -->"
          direction: last
      - name: Comment Create/Update
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.number }}
          comment-id: ${{ steps.previous-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- deployment #${{ github.event.number }} -->
            🚀 Deployed a preview for `${{ github.sha }}`:

            ${{ steps.deployment.outputs.url }}
